"""ARTools public package interface."""

from importlib.metadata import PackageNotFoundError, version

from .astronomical import (
    AstronomicalCrossScanService,
    AstronomicalSourceNotFoundError,
    AstronomicalSourceResolutionError,
    AstronomicalTrackingService,
    AstronomyDependencyError,
    AstropyAstronomicalPositionCalculator,
    MappingAstronomicalSourceResolver,
    SimbadAstronomicalSourceResolver,
    create_default_astronomical_cross_scan_service,
    create_default_astronomical_tracking_service,
)
from .auxiliary_telescope import AuxiliaryTelescopeTrajectoryWriter
from .cross_scan import (
    CrossScanParameters,
    generate_cross_scan_trajectory,
    normalize_cross_scan_point_count,
)
from .satellite import (
    CELESTRAK_GP_ENDPOINT,
    CelesTrakTleCatalog,
    PycrafSatellitePositionCalculator,
    PycrafSatelliteRefractionCalculator,
    SatelliteAtmosphericProfile,
    SatelliteCrossScanService,
    SatelliteDependencyError,
    SatelliteNotFoundError,
    SatellitePosition,
    SatelliteRefractionParameters,
    SatelliteTarget,
    SatelliteTrackingService,
    TleCatalogError,
    TleData,
    TleFormatError,
    create_default_satellite_cross_scan_service,
    create_default_satellite_tracking_service,
    normalize_satellite_azimuth_deg,
    parse_tle_catalog,
)
from .solar_system import (
    AstropySolarSystemPositionCalculator,
    SolarSystemBody,
    SolarSystemCrossScanService,
    SolarSystemBodyTarget,
    SolarSystemDependencyError,
    SolarSystemTrackingService,
    UnsupportedSolarSystemBodyError,
    create_default_solar_system_cross_scan_service,
    create_default_solar_system_tracking_service,
)
from .configuration import AUXILIARY_TELESCOPE, SRT_SITE
from .domain import (
    AtmosphericParameters,
    AstronomicalSourceTarget,
    ControlledSystem,
    EquatorialCoordinates,
    HorizontalCoordinates,
    ObserverSite,
    TargetFamily,
    Trajectory,
    TrajectoryMode,
    TrajectoryPoint,
    TrajectoryRequestParameters,
)

try:
    __version__ = version("artools")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "AUXILIARY_TELESCOPE",
    "AtmosphericParameters",
    "CELESTRAK_GP_ENDPOINT",
    "CelesTrakTleCatalog",
    "AstronomicalCrossScanService",
    "AstronomicalSourceNotFoundError",
    "AstronomicalSourceResolutionError",
    "AstronomicalSourceTarget",
    "AstronomicalTrackingService",
    "AstronomyDependencyError",
    "AstropyAstronomicalPositionCalculator",
    "AstropySolarSystemPositionCalculator",
    "SolarSystemBody",
    "SolarSystemCrossScanService",
    "SolarSystemBodyTarget",
    "SolarSystemDependencyError",
    "SolarSystemTrackingService",
    "UnsupportedSolarSystemBodyError",
    "create_default_solar_system_cross_scan_service",
    "create_default_solar_system_tracking_service",
    "SRT_SITE",
    "AuxiliaryTelescopeTrajectoryWriter",
    "ControlledSystem",
    "CrossScanParameters",
    "EquatorialCoordinates",
    "HorizontalCoordinates",
    "MappingAstronomicalSourceResolver",
    "ObserverSite",
    "PycrafSatellitePositionCalculator",
    "PycrafSatelliteRefractionCalculator",
    "SatelliteAtmosphericProfile",
    "SatelliteCrossScanService",
    "SatelliteDependencyError",
    "SatelliteNotFoundError",
    "SatellitePosition",
    "SatelliteRefractionParameters",
    "SatelliteTarget",
    "SatelliteTrackingService",
    "SimbadAstronomicalSourceResolver",
    "TargetFamily",
    "Trajectory",
    "TrajectoryMode",
    "TrajectoryPoint",
    "TrajectoryRequestParameters",
    "TleCatalogError",
    "TleData",
    "TleFormatError",
    "create_default_satellite_cross_scan_service",
    "create_default_satellite_tracking_service",
    "generate_cross_scan_trajectory",
    "normalize_cross_scan_point_count",
    "normalize_satellite_azimuth_deg",
    "parse_tle_catalog",
    "create_default_astronomical_cross_scan_service",
    "create_default_astronomical_tracking_service",
    "__version__",
]
